### ISSUE TITLE
not compatible with Authoring tool?

### ISSUE THREAD

**Issue by samumist** [kunjsharma/adapt-animation-hotspot#1]
Tried to test it with the Authoring tool, but failed to upload.
The error message was `Unrecognized plugin type for package adapt-animation-hotspot`. 

I've been able to fix this by modify the `bower.json` file and upload the plugin successfully. However, when try to apply this plugin in a block, a `constructorFn is not a constructor` pops up. Seems some problem with the `properties.schema`.
![1f0951df-5977-4450-b780-99a06a7525d8](https://user-images.githubusercontent.com/3883086/29977018-9094e540-8f6e-11e7-9fc1-f786015f0aea.jpg)

**Comment by kunjsharma** [comment]
Thanks for point it out! I did not use authoring tool, though I've tested it in framework v2.0.3. If you find any solution, please fork it, also I am looking this issue.

**Comment by samumist** [comment]
I'll see if I can make it work with the authoring tool.

**Comment by memeteli** [comment]
@samumist , any progress?

**Comment by samumist** [comment]
@fkcailiniyazi , noh, I've not been working with adapt for quite some time. Sorry for the late reply.
